//
// ClassShortNameType.cs
//
// This file was generated by XMLSpy 2006sp2 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//


using Altova.Types;

namespace PersonResults
{

	public class ClassShortNameType : SchemaString
	{
		public static string[] sEnumValues = {
			"A-Legendar",
			"H 21-",
			"H 21-E",
			"H17",
			"H21",
			"H21A",
			"Res",
		};

		public enum EnumValues
		{
			eA_Legendar = 0, /* A-Legendar */
			eH_21_ = 1, /* H 21- */
			eH_21_E = 2, /* H 21-E */
			eH17 = 3, /* H17 */
			eH21 = 4, /* H21 */
			eH21A = 5, /* H21A */
			eRes = 6, /* Res */
			EnumValueCount
		};

		public ClassShortNameType() : base()
		{
		}

		public ClassShortNameType(string newValue) : base(newValue)
		{
			Validate();
		}

		public ClassShortNameType(SchemaString newValue) : base(newValue)
		{
			Validate();
		}

		public static int GetEnumerationCount()
		{
			return sEnumValues.Length;
		}

		public static string GetEnumerationValue(int index)
		{
			return sEnumValues[index];
		}

		public static bool IsValidEnumerationValue(string val)
		{
			foreach (string s in sEnumValues)
			{
				if (val == s)
					return true;
			}
			return false;
		}

		public void Validate()
		{

			if (!IsValidEnumerationValue(ToString()))
				throw new System.Exception("Value of ClassShortName is invalid.");
		}
	}
}
