//
// DateType.cs
//
// This file was generated by XMLSpy 2006sp2 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//


using Altova.Types;

namespace PersonResults
{

	public class DateType : SchemaString
	{
		public static string[] sEnumValues = {
			"1977-11-29",
			"2009-10-27",
			"2012-03-27",
			"2012-03-28",
			"2012-04-20",
			"2012-04-22",
			"2012-04-23",
			"2012-04-27",
			"2012-04-28",
			"2012-04-29",
			"2012-04-30",
			"2012-05-19",
			"2012-05-20",
			"2012-05-21",
			"2012-05-26",
			"2012-05-27",
			"2012-05-28",
			"2012-05-29",
			"2012-05-30",
			"2012-06-02",
			"2012-06-03",
			"2012-06-04",
			"2012-06-05",
			"2012-06-06",
			"2012-06-08",
			"2012-08-31",
			"2012-09-01",
			"2012-09-26",
			"2012-10-10",
			"2012-10-15",
			"2012-10-17",
			"2012-10-24",
			"2012-10-26",
		};

		public enum EnumValues
		{
			e1977_11_29 = 0, /* 1977-11-29 */
			e2009_10_27 = 1, /* 2009-10-27 */
			e2012_03_27 = 2, /* 2012-03-27 */
			e2012_03_28 = 3, /* 2012-03-28 */
			e2012_04_20 = 4, /* 2012-04-20 */
			e2012_04_22 = 5, /* 2012-04-22 */
			e2012_04_23 = 6, /* 2012-04-23 */
			e2012_04_27 = 7, /* 2012-04-27 */
			e2012_04_28 = 8, /* 2012-04-28 */
			e2012_04_29 = 9, /* 2012-04-29 */
			e2012_04_30 = 10, /* 2012-04-30 */
			e2012_05_19 = 11, /* 2012-05-19 */
			e2012_05_20 = 12, /* 2012-05-20 */
			e2012_05_21 = 13, /* 2012-05-21 */
			e2012_05_26 = 14, /* 2012-05-26 */
			e2012_05_27 = 15, /* 2012-05-27 */
			e2012_05_28 = 16, /* 2012-05-28 */
			e2012_05_29 = 17, /* 2012-05-29 */
			e2012_05_30 = 18, /* 2012-05-30 */
			e2012_06_02 = 19, /* 2012-06-02 */
			e2012_06_03 = 20, /* 2012-06-03 */
			e2012_06_04 = 21, /* 2012-06-04 */
			e2012_06_05 = 22, /* 2012-06-05 */
			e2012_06_06 = 23, /* 2012-06-06 */
			e2012_06_08 = 24, /* 2012-06-08 */
			e2012_08_31 = 25, /* 2012-08-31 */
			e2012_09_01 = 26, /* 2012-09-01 */
			e2012_09_26 = 27, /* 2012-09-26 */
			e2012_10_10 = 28, /* 2012-10-10 */
			e2012_10_15 = 29, /* 2012-10-15 */
			e2012_10_17 = 30, /* 2012-10-17 */
			e2012_10_24 = 31, /* 2012-10-24 */
			e2012_10_26 = 32, /* 2012-10-26 */
			EnumValueCount
		};

		public DateType() : base()
		{
		}

		public DateType(string newValue) : base(newValue)
		{
			Validate();
		}

		public DateType(SchemaString newValue) : base(newValue)
		{
			Validate();
		}

		public static int GetEnumerationCount()
		{
			return sEnumValues.Length;
		}

		public static string GetEnumerationValue(int index)
		{
			return sEnumValues[index];
		}

		public static bool IsValidEnumerationValue(string val)
		{
			foreach (string s in sEnumValues)
			{
				if (val == s)
					return true;
			}
			return false;
		}

		public void Validate()
		{

			if (!IsValidEnumerationValue(ToString()))
				throw new System.Exception("Value of Date is invalid.");
		}
	}
}
