//
// EventClassificationIdType.cs
//
// This file was generated by XMLSpy 2006sp2 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//


using Altova.Types;

namespace PersonResults
{

	public class EventClassificationIdType : SchemaInt
	{
		public static string[] sEnumValues = {
			"2",
			"3",
			"4",
			"5",
		};

		public enum EnumValues
		{
			e2 = 0, /* 2 */
			e3 = 1, /* 3 */
			e4 = 2, /* 4 */
			e5 = 3, /* 5 */
			EnumValueCount
		};

		public EventClassificationIdType() : base()
		{
		}

		public EventClassificationIdType(string newValue) : base(newValue)
		{
			Validate();
		}

		public EventClassificationIdType(SchemaInt newValue) : base(newValue)
		{
			Validate();
		}

		public static int GetEnumerationCount()
		{
			return sEnumValues.Length;
		}

		public static string GetEnumerationValue(int index)
		{
			return sEnumValues[index];
		}

		public static bool IsValidEnumerationValue(string val)
		{
			foreach (string s in sEnumValues)
			{
				if (val == s)
					return true;
			}
			return false;
		}

		public void Validate()
		{

			if (!IsValidEnumerationValue(ToString()))
				throw new System.Exception("Value of EventClassificationId is invalid.");
		}
	}
}
