//
// ResultPositionType.cs
//
// This file was generated by XMLSpy 2006sp2 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//


using Altova.Types;

namespace PersonResults
{

	public class ResultPositionType : SchemaInt
	{
		public static string[] sEnumValues = {
			"1",
			"10",
			"14",
			"16",
			"2",
			"20",
			"22",
			"4",
			"40",
			"72",
		};

		public enum EnumValues
		{
			e1 = 0, /* 1 */
			e10 = 1, /* 10 */
			e14 = 2, /* 14 */
			e16 = 3, /* 16 */
			e2 = 4, /* 2 */
			e20 = 5, /* 20 */
			e22 = 6, /* 22 */
			e4 = 7, /* 4 */
			e40 = 8, /* 40 */
			e72 = 9, /* 72 */
			EnumValueCount
		};

		public ResultPositionType() : base()
		{
		}

		public ResultPositionType(string newValue) : base(newValue)
		{
			Validate();
		}

		public ResultPositionType(SchemaInt newValue) : base(newValue)
		{
			Validate();
		}

		public static int GetEnumerationCount()
		{
			return sEnumValues.Length;
		}

		public static string GetEnumerationValue(int index)
		{
			return sEnumValues[index];
		}

		public static bool IsValidEnumerationValue(string val)
		{
			foreach (string s in sEnumValues)
			{
				if (val == s)
					return true;
			}
			return false;
		}

		public void Validate()
		{

			if (!IsValidEnumerationValue(ToString()))
				throw new System.Exception("Value of ResultPosition is invalid.");
		}
	}
}
