//
// WebURLType.cs
//
// This file was generated by XMLSpy 2006sp2 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//


using Altova.Types;

namespace PersonResults
{

	public class WebURLType : SchemaString
	{
		public static string[] sEnumValues = {
			"http://nydalen.idrett.no/orientering/2012/10/15/retronatta-2012/",
			"http://nydalen.idrett.no/orientering/arrangementer/harry-lagert/",
			"http://nydalen.idrett.no/orientering/arrangementer/klubbmesterskap/",
			"http://student.umb.no/~orientering/ascup/2012/abnfc12.php",
			"http://www.fossumif.no/nmhelg2012/hjem/",
			"http://www.indre-ostfold.com",
			"http://www.kolweb.no/pinselopet/hjem/",
			"http://www.norwegianspring.no/",
			"http://www.ok-moss.no/kjappen12/",
			"http://www.oppsal.com",
			"http://www.tyrving.idrett.no/o",
		};

		public enum EnumValues
		{
			ehttp___nydalen_idrett_no_orientering_2012_10_15_retronatta_2012_ = 0, /* http://nydalen.idrett.no/orientering/2012/10/15/retronatta-2012/ */
			ehttp___nydalen_idrett_no_orientering_arrangementer_harry_lagert_ = 1, /* http://nydalen.idrett.no/orientering/arrangementer/harry-lagert/ */
			ehttp___nydalen_idrett_no_orientering_arrangementer_klubbmestersk = 2, /* http://nydalen.idrett.no/orientering/arrangementer/klubbmesterskap/ */
			ehttp___student_umb_no__orientering_ascup_2012_abnfc12_php = 3, /* http://student.umb.no/~orientering/ascup/2012/abnfc12.php */
			ehttp___www_fossumif_no_nmhelg2012_hjem_ = 4, /* http://www.fossumif.no/nmhelg2012/hjem/ */
			ehttp___www_indre_ostfold_com = 5, /* http://www.indre-ostfold.com */
			ehttp___www_kolweb_no_pinselopet_hjem_ = 6, /* http://www.kolweb.no/pinselopet/hjem/ */
			ehttp___www_norwegianspring_no_ = 7, /* http://www.norwegianspring.no/ */
			ehttp___www_ok_moss_no_kjappen12_ = 8, /* http://www.ok-moss.no/kjappen12/ */
			ehttp___www_oppsal_com = 9, /* http://www.oppsal.com */
			ehttp___www_tyrving_idrett_no_o = 10, /* http://www.tyrving.idrett.no/o */
			EnumValueCount
		};

		public WebURLType() : base()
		{
		}

		public WebURLType(string newValue) : base(newValue)
		{
			Validate();
		}

		public WebURLType(SchemaString newValue) : base(newValue)
		{
			Validate();
		}

		public static int GetEnumerationCount()
		{
			return sEnumValues.Length;
		}

		public static string GetEnumerationValue(int index)
		{
			return sEnumValues[index];
		}

		public static bool IsValidEnumerationValue(string val)
		{
			foreach (string s in sEnumValues)
			{
				if (val == s)
					return true;
			}
			return false;
		}

		public void Validate()
		{

			if (!IsValidEnumerationValue(ToString()))
				throw new System.Exception("Value of WebURL is invalid.");
		}
	}
}
